name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm test

      - name: Build
        run: npm run build

      # 🔥 Aqui entra a notificação do deploy para o Sleuth
      - name: Notificar deploy no Sleuth
        if: success()
        run: |
          curl -X POST "https://app.sleuth.io/api/1/deployments" \
          -H "Authorization: Bearer ${{ secrets.SLEUTH_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{
            "environment": "production",
            "sha": "'${{ github.sha }}'",
            "repo": "isageorgete/exeplo3-sleuth"
          }'
